// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"go-payments-api/internal/application"
	"go-payments-api/internal/application/usecase"
	"go-payments-api/internal/infrastructure/api"
	"go-payments-api/internal/infrastructure/api/handler"
	"go-payments-api/internal/test"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

func InitializeApi() (*api.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	server := provideApiServer()
	presenter := provideApiPresenter()
	health := &handler.Health{
		Presenter: presenter,
	}
	db, cleanup, err := ProvidePostgresConnection()
	if err != nil {
		return nil, nil, err
	}
	paymentRepository := ProvidePaymentRepository(db)
	publisher := provideKafkaPublisher()
	createPaymentImplementation := usecase.NewCreatePaymentUseCase(paymentRepository, publisher)
	createPayment := &handler.CreatePayment{
		UseCase:   createPaymentImplementation,
		Presenter: presenter,
	}
	apiApplication := &api.Application{
		BaseApp:              app,
		Server:               server,
		HealthHandler:        health,
		CreatePaymentHandler: createPayment,
	}
	return apiApplication, func() {
		cleanup()
	}, nil
}

func InitilizeTests(mockCtrl *gomock.Controller) (*test.Application, func(), error) {
	logger := provideLogger()
	tracer := provideTracer()
	app := &application.App{
		Logger: logger,
		Tracer: tracer,
	}
	server := provideApiServer()
	presenter := provideApiPresenter()
	health := &handler.Health{
		Presenter: presenter,
	}
	db, cleanup, err := ProvidePostgresConnection()
	if err != nil {
		return nil, nil, err
	}
	paymentRepository := ProvidePaymentRepository(db)
	publisher := provideKafkaPublisher()
	createPaymentImplementation := usecase.NewCreatePaymentUseCase(paymentRepository, publisher)
	createPayment := &handler.CreatePayment{
		UseCase:   createPaymentImplementation,
		Presenter: presenter,
	}
	apiApplication := &api.Application{
		BaseApp:              app,
		Server:               server,
		HealthHandler:        health,
		CreatePaymentHandler: createPayment,
	}
	testApplication := &test.Application{
		BaseApp:  app,
		Api:      apiApplication,
		MockCtrl: mockCtrl,
	}
	return testApplication, func() {
		cleanup()
	}, nil
}

// wire.go:

var wireApiSet = wire.NewSet(
	commonSet,
	repositoriesSet,
	messagingSet,
	usecasesSet,

	apiMiddlewaresSet,
	apiHandlersSet, wire.Struct(new(api.Application), "*"),
)

var wireTestSet = wire.NewSet(
	commonSet,
	repositoriesSet,
	messagingSet,
	usecasesSet,

	apiMiddlewaresSet,
	apiHandlersSet, wire.Struct(new(api.Application), "*"), wire.Struct(new(test.Application), "*"),
)
